# Generated by Django 5.2.5 on 2025-08-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vLogradouro', models.CharField(max_length=80)),
                ('vComplemento', models.CharField(blank=True, max_length=50, null=True)),
                ('vBairro', models.CharField(max_length=40)),
                ('vNumero', models.CharField(max_length=10)),
                ('cUF', models.CharField(max_length=2)),
            ],
        ),
    ]
