# Generated by Django 5.2.5 on 2025-08-13 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vDesc_veiculo', models.CharField(max_length=35)),
                ('vPlaca', models.CharField(max_length=7, unique=True)),
                ('nValor', models.DecimalField(decimal_places=3, max_digits=15)),
                ('iCod_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
        ),
    ]
