# Generated by Django 5.2.5 on 2025-08-13 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vNome_fantasia', models.CharField(max_length=80)),
                ('vNome_razao_social', models.CharField(max_length=80)),
                ('vCnpj', models.CharField(max_length=14, unique=True)),
                ('vEmail', models.CharField(max_length=40)),
                ('vObservacao', models.CharField(blank=True, max_length=200, null=True)),
                ('iCod_endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco')),
            ],
        ),
    ]
