# Generated by Django 5.2.5 on 2025-08-14 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='iCod_endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco'),
        ),
    ]
