# Generated by Django 5.2.5 on 2025-08-14 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_empresa_vcnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='vCnpj',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(14, message='O CNPJ deve ter 14 dígitos')]),
        ),
    ]
